### ISSUE TITLE
db

### ISSUE THREAD

**Issue by Axkaban** [danielle-h/bapi-cp3-expresso#2]
sqlite was used for its compatibility, but if you're interested in keeping on working with databases MySQL or PostgreSQL are very common management systems that are very relatable through SQL commands and most of their methods are alike. If you ever open someone else's Express app, you will also usually see server.js as index.js which is just conventional.

**Comment by danielle-h** [comment]
Thanks for the information. I really was wondering about that as I usually saw index.js.
