### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Axkaban** [danielle-h/bapi-cp3-expresso#3]
I love that you commented per section, I know that setting up server.js is kind of plug an play but if we are not attentive enough, serious bugs could be lay there, that is why I enjoy reading this lines:
[https://github.com/danielle-h/bapi-cp3-expresso/blob/master/capstone-project-2-expresso/server.js#L4-L15](https://github.com/danielle-h/bapi-cp3-expresso/blob/master/capstone-project-2-expresso/server.js#L4-L15)

**Comment by danielle-h** [comment]
Thanks!
