### ISSUE TITLE
server (api)

### ISSUE THREAD

**Issue by Axkaban** [danielle-h/bapi-cp3-expresso#4]
Lines like this:
[https://github.com/danielle-h/bapi-cp3-expresso/blob/master/capstone-project-2-expresso/server/api.js#L8-L9](https://github.com/danielle-h/bapi-cp3-expresso/blob/master/capstone-project-2-expresso/server/api.js#L8-L9)
can be rewritten like:
`apiRouter.use ('/employees', require('./employees.js'));` saving you space and giving it a cleaner look.

**Comment by danielle-h** [comment]
Thanks, didn't occur to me for some reason. Would really make code cleaner and more readable.
