### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [danielle-h/bapi-cp3-expresso#5]
Fantastic work! Now, a common arrangement is the [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) (Models, Views, Controllers) approach. as you have your source directory for all your components from React, you will also have a migration directory with your seeds, a controllers directory with all the respective files with methods for req/res (ie. employees_controller.js) and its index.js to route from the controller out to a main router, also a modules directory where you have files that carry methods called from a controller and connecting the query to the database (like a middle man, ie. employees.js), and in the main directory a index.js(as a mention before, like your server.js), as well as a router.js, the main routes to your front end and redirecting information from index.js from controllers. I know it sounds complicated and maybe like a lot of work, but makes it more modular and dry, since you set every file with one sole purpose, just like React does with every component, at the end route.js takes everything and sends it to your server(index.js or server.js) to be rendered in the right place. It also helps to search through, comment, and locate where problems, errors, or bugs could be. Congrats! You've finished the Build APIs From Scratch course! Now, to try different architectural patterns, check if MVC is your favorite or if you rather follow any other process. It's time to experiment! Happy holidays.

**Comment by danielle-h** [comment]
Thanks for the tip, I'll check it out! Have a lovely year.
